### ISSUE TITLE
Getting Exception

### ISSUE THREAD

**Issue by karim-khalil** [davisnando/ticketswap_bot#2]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"Menubar__NavList-sc-1lcf4ys-2"}

Really appreciate your code davisnando, I'm new to Python, how can I fix this?

**Comment by killer4nl** [comment]
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"Menubar__NavList-sc-1lcf4ys-2"}
> 
> Really appreciate your code davisnando, I'm new to Python, how can I fix this?

pm me

**Comment by simonravel** [comment]
Same issue, I've sent you a friend request on discord:

`(.env) simon@MacBook-Pro-5 ticketswap_bot % python main.py
Facebook username: xxx
Facebook password: 
Traceback (most recent call last):
  File "/Users/simon/Documents/ticketswap_bot/main.py", line 164, in <module>
    t = TicketSwap()
  File "/Users/simon/Documents/ticketswap_bot/main.py", line 21, in __init__
    self.login()
  File "/Users/simon/Documents/ticketswap_bot/main.py", line 29, in login
    login_button = driver.find_element_by_class_name(
  File "/Users/simon/Documents/ticketswap_bot/.env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 488, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/Users/simon/Documents/ticketswap_bot/.env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/simon/Documents/ticketswap_bot/.env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/Users/simon/Documents/ticketswap_bot/.env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"Menubar__NavList-sc-1lcf4ys-2"}
  (Session info: chrome=99.0.4844.84)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.16.0 x86_64)
`

**Comment by davisnando** [comment]
I've updated the whole bot so that it works agains. See the readme how to get it
